[project]
name = "pixidemo"
version = "0.1.0"
description = "Add a short description here"
authors = ["liquidcarbon <akscrps@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
compile = "gcc -shared -o src/mylib.so src/mylib.c"
start = {cmd = "python src/main.py", depends_on = "compile"}
jn = {cmd = "jupyter notebook --ip=0.0.0.0 --no-browser --allow-root", depends_on = "start"}
s3ls = {cmd = "aws s3 ls $1"}

[dependencies]
gcc = "13.2.0.*"
python = "3.11.*"
numpy = "1.26.0.*"
notebook = "6.5.6.*"
